theme: jekyll-theme-slate
title: Egon.io–The Domain Story Modeler
description: A open-source tool for visualizing domain stories.
show_downloads: true
github:
  repository_url: https://github.com/WPS/domain-story-modeler
  zip_url: https://github.com/WPS/domain-story-modeler/releases/download/v1.2.1/Domain.Story.Modeler.v1.2.1.zip
  tar_url: