# frozen_string_literal: true

source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-include-cache", group: :jekyll_plugins

#gem "jekyll", "~> 3.9"

#gem "webrick", "~> 1.7"

#gem "minimal-mistakes-jekyll", "~> 4.24"
